AWSTemplateFormatVersion: '2010-09-09'
Description: Nested stack for creating toy checklist application public dns zone
Parameters:
  RootDomainName:
    Description: Root DNS name to be used for the toy checklist aws serverless application
    Type: String
    MinLength: 1
    MaxLength: 64
    AllowedPattern: (?=^.{1,254}$)(^(?:(?!\d+\.|-)[a-zA-Z0-9_\-]{1,63}(?<!-)\.?)+(?:[a-zA-Z]{2,})$)
    ConstraintDescription: Must be a valid fully-qualified domain name.
    Default: dcorp.info
  WWWDomainName:
    Description: S3 Bucket Domain Name to be used for redirecting requests to www.RootDomainName
    Type: String
    MinLength: 1
    MaxLength: 64
    AllowedPattern: (?=^.{1,254}$)(^(?:(?!\d+\.|-)[a-zA-Z0-9_\-]{1,63}(?<!-)\.?)+(?:[a-zA-Z]{2,})$)
    ConstraintDescription: Must be a valid fully-qualified domain name.
    Default: www.dcorp.info
  ParentStackName:
    Description: Parent stack name
    Type: String
    MinLength: 1
    MaxLength: 64
    Default: toychecklist
  BillingCode:
    Description: Billing code to be tagged on the resources of the toy checklist aws serverless application
    Type: String
    MinLength: 1
    MaxLength: 64
    Default: toychecklist
Mappings:
  RegionMap:
    us-east-1:
      S3hostedzoneID: Z3AQBSTGFYJSTF
      websiteendpoint: s3-website-us-east-1.amazonaws.com
    us-west-1:
      S3hostedzoneID: Z2F56UZL2M1ACD
      websiteendpoint: s3-website-us-west-1.amazonaws.com
    us-west-2:
      S3hostedzoneID: Z3BJ6K6RIION7M
      websiteendpoint: s3-website-us-west-2.amazonaws.com
    eu-west-1:
      S3hostedzoneID: Z1BKCTXD74EZPE
      websiteendpoint: s3-website-eu-west-1.amazonaws.com
    ap-southeast-1:
      S3hostedzoneID: Z3O0J2DXBE1FTB
      websiteendpoint: s3-website-ap-southeast-1.amazonaws.com
    ap-southeast-2:
      S3hostedzoneID: Z1WCIGYICN2BYD
      websiteendpoint: s3-website-ap-southeast-2.amazonaws.com
    ap-northeast-1:
      S3hostedzoneID: Z2M4EHUR26P7ZW
      websiteendpoint: s3-website-ap-northeast-1.amazonaws.com
    sa-east-1:
      S3hostedzoneID: Z31GFT0UA1I2HV
      websiteendpoint: s3-website-sa-east-1.amazonaws.com
Resources:
  RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    DeletionPolicy: Retain
    Properties:
      HostedZoneName: !Sub
          - ${Domain}.
          - Domain: !Ref RootDomainName
      Comment: Zone apex alias.
      RecordSets:
      -
        Name: !Ref RootDomainName
        Type: A
        AliasTarget:
          HostedZoneId: !FindInMap [ RegionMap, !Ref 'AWS::Region', S3hostedzoneID]
          DNSName: !FindInMap [ RegionMap, !Ref 'AWS::Region', websiteendpoint]
      -
        Name: !Sub
            - www.${Domain}
            - Domain: !Ref RootDomainName
        Type: CNAME
        TTL: 900
        ResourceRecords:
        - !Ref WWWDomainName
